language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm-nightly

services:
    - memcached

before_script:
  #HHVM flips about phpenv
  - if [ "`phpenv version-name`" != "hhvm-nightly" ]; then echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  #Only 5.4 uses APC
  - if [ "`phpenv version-name`" == "5.4" ] && [ "`phpenv version-name`" != "hhvm-nightly" ]; then echo -e "extension = apc.so\napc.enabled=1\napc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  #+5.5 uses APCU
  - if [ "`phpenv version-name`" != "5.4" ] && [ "`phpenv version-name`" != "hhvm-nightly" ]; then printf "\n"| pecl install apcu-beta && echo -e "extension = apcu.so\napc.enabled=1\napc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - composer install

script:
  - phpunit tests/